substitutions:
  _PROJECT_ID: 'data-ops-466417'
  _FUNCTION_BUCKET: 'tf-cloud-functions-bucket'
  _REGION: 'southamerica-east1'
  
logsBucket: 'cloudbuild-logs-cloud-function-466417'
timeout: 3600s

steps:

  # 1. Chama o build da função
  #    Substitui os parâmetros _FUNCTION_BUCKET e _REGION
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - builds
      - submit
      - --config=cloudbuild.yaml
      - --substitutions=_FUNCTION_BUCKET=$FUNCTION_BUCKET,_REGION=$REGION
      - .

  # 2. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 3. Terraform Plan
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # 4. Terraform Apply
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'
