substitutions:
  _FUNCTION_NAME: 'fnc-kaggle-sample-sales' # Altere de acordo com a funcao a ser carregada

logsBucket: 'cloudbuild-logs-cloud-function-466417'
timeout: 3600s

steps:

  # 1. Chama o build da função
  # Altere o _FUNCTION_NAME de acordo com a funcao a ser carregada
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - builds
      - submit
      - ./functions/$_FUNCTION_NAME/cloudbuild.yaml
      - .
      
  # 2. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 3. Terraform Plan
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # 4. Terraform Apply
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'
