substitutions:
  _FUNCTION_NAME: 'fnc-kaggle-sample-sales'     # Altere de acordo com a funcao a ser carregada
  _FUNCTION_BUCKET: 'tf-cloud-functions-bucket'
  _PROJECT_ID: "data-ops-466417"
  _REGION: 'southamerica-east1'  # Altere de acordo com a regiao

logsBucket: 'cloudbuild-logs-cloud-function-466417'
timeout: 3600s

steps:

  # 0. Verifica e deleta a função existente
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verificando se a função $_FUNCTION_NAME existe na região $_REGION e no projeto $_PROJECT_ID..."
        if gcloud functions describe $_FUNCTION_NAME \
            --region=$_REGION \
            --gen2 \
            --project=$_PROJECT_ID >/dev/null 2>&1; then
          echo "Função encontrada. Deletando..."
          gcloud functions delete $_FUNCTION_NAME \
            --region=$_REGION \
            --gen2 \
            --quiet \
            --project=$_PROJECT_ID
        else
          echo "Função não encontrada. Pulando deleção."
        fi

  # 1. Zipa a pasta da funcao com suas dependencias
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        cd functions/$_FUNCTION_NAME
        zip -r ../../$_FUNCTION_NAME.zip .

  # 2. Copia o zip para o bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '$_FUNCTION_NAME.zip', 'gs://$_FUNCTION_BUCKET/$_FUNCTION_NAME.zip']

  # 3. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 4. Terraform Plan
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    dir: 'terraform'

  # 5. Terraform Apply
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform'
