substitutions:
  _FUNCTION_BUCKET: 'tf-cloud-functions-bucket'

steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt -t ./packages
        cp main.py ./packages/
        cd packages && zip -r ../fnc-kaggle-sample-sales.zip .

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'fnc-kaggle-sample-sales.zip', 'gs://$_FUNCTION_BUCKET/fnc-kaggle-sample-sales.zip']
